### ISSUE TITLE
Icon dialog must have a callback

### ISSUE THREAD

**Issue by joao-moniz** [maltaisn/icondialoglib#36] opened 2020-04-22 00:59 UTC
Create a icon dialog from Fragment does not work.

    public class DialogFrgment_AdicionarCategoriaFluxoDeCaixa extends BottomSheetDialogFragment implements IconDialog.Callback{

    private static final String ICON_DIALOG_TAG = "icon-dialog";

    private IconPack iconPack;
    private EditText edDescricao;
    private ImageButton imColorPIcker, imIconPicker;
    private IconDialog iconDialog;
    private FragmentManager fm;

    public static DialogFrgment_AdicionarCategoriaFluxoDeCaixa newInstance() {
        DialogFrgment_AdicionarCategoriaFluxoDeCaixa f = new DialogFrgment_AdicionarCategoriaFluxoDeCaixa();
        //f.setCancelable(false);
        f.setShowsDialog(true);
        return f;
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        fm = this.getFragmentManager();
        iconDialog = (IconDialog) fm.findFragmentByTag(ICON_DIALOG_TAG);
        if(iconDialog == null){
            iconDialog = IconDialog.newInstance(new IconDialogSettings.Builder().build());
        }
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.fragment_adicionar_categoria_fluxo_de_caixa, container, false);
        imIconPicker = (ImageButton) v.findViewById(R.id.imIconPicker_fragmentAdicionarCategoriaFlucoDeCaixa);

        imIconPicker.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                iconDialog.show(fm, ICON_DIALOG_TAG);
            }
        });
        return v;
    }

    @Nullable
    @Override
    public IconPack getIconDialogIconPack() {
        return ((CustomApplication) getActivity().getApplication()).getIconPack();
    }

    @Override
    public void onIconDialogIconsSelected(@NonNull IconDialog dialog, @NonNull List<Icon> icons) {
        // Show a toast with the list of selected icon IDs.
        StringBuilder sb = new StringBuilder();
        for (Icon icon : icons) {
            sb.append(icon.getId());
            sb.append(", ");
        }
        sb.delete(sb.length() - 2, sb.length());
        Toast.makeText(getActivity(), "Icons selected: " + sb, Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onIconDialogCancelled() {}
 }

Error :  java.lang.IllegalStateException: Icon dialog must have a callback.
        at com.maltaisn.icondialog.IconDialog.getCallback(IconDialog.kt:354)
        at com.maltaisn.icondialog.IconDialog.getIconPack(IconDialog.kt:63)

**Comment by maltaisn** [comment] 2020-04-22 01:50
Duplicate of #14. Replace this line:
```java
fm = this.getFragmentManager();
```
With this one:
```java
fm = this.getChildFragmentManager();
```
If you take a look at [how the callback is resolved](https://github.com/maltaisn/icondialoglib/blob/master/lib/src/main/kotlin/com/maltaisn/icondialog/IconDialog.kt#L350), you'll see the calling fragment must either be:
- the parent fragment, for which you need if you use `childFragmentManager` when showing the dialog;
- the target fragment, for which you need to set with `setTargetFragment(this)` on the icon dialog.

**Closed as completed by maltaisn** 2020-04-22 01:50 UTC
